version: '3'
services:
  exercise1:
    build: .
    ports:
      - "9001:9001"
    environment:
      - URL=messageapp
      - SENDPORT=3000
  messageapp:
    image: "cabify/backend-bootcamp-messageapp:latest"
    ports:
      - "3000:3000"
