version: '3'
services:
  # service:
  #   build: ./service/.
  #   image: exercise1
  #   ports:
  #     - "9001:9001"
  #   environment:
  #     - URL=messageapp
  #     - SENDPORT=3000
  #     - PORT=9001
  #   depends_on:
  #     - "mongodb"
  #   links:
  #     - "mongodb"
  messageapp:
    image: "cabify/backend-bootcamp-messageapp:latest"
    ports:
      - "3000:3000"
  mongodb1:
    image: mongo:latest
    container_name: "mongodb1"
    volumes:
      - ./data/db1:/data/db1
    ports:
      - 27017:27017
  mongodb2:
    image: mongo:latest
    container_name: "mongodb2"
    volumes:
      - ./data/db2:/data/db2
    ports:
      - 27018:27017